# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a0552c397f7fa11a528c70aa4d76782dff54dd94e2894819fad13fa69626b549091fe66a758df2ee13230a5115b72d1f8afd0f848374e577d207660b6276db2

test:
  secret_key_base: e01b1b3b7d697452f91c64513b8edc85217e8f574548369d661efc0375e09b6ce13fce637493ba9098582cb33129bfa4b8aeecd1c312fa23ce7f23a65ae9f10b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
